apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb-standalone
    spec:
      volumes:
        - name:  mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
      containers:
      - name: mongodb-standalone
        image: mongo
        volumeMounts:
          - mountPath: /data/db
            name: mongo-pv-storage